Neos:
  Neos:
    fusion:
      autoInclude:
        Soee.CookieConsent: true
    userInterface:
      translation:
        autoInclude:
          'Soee.CookieConsent': ['NodeTypes/*', 'Settings']
Soee:
  CookieConsent:
    includeCss: true
    includeJavaScript: true
    palettes:
# the complete pallet configuration looks like this
#      pallet-name:
#        label: 'Label name visible inside properties inspector'
#        colors:
#          popup:
#            background: '#000'
#            text: '#fff'
#            link: '#fff'
#          button:
#            background: 'transparent'
#            border: '#f8e71c'
#            text: '#f8e71c'
#          highlight:
#            background: '#f8e71c'
#            border: '#f8e71c'
#            text: '#000000'
      black-yellow:
        label: 'Soee.CookieConsent:Settings:palettes.black-yellow'
        colors:
          popup:
            background: '#000'
          button:
            background: '#f1d600'
      aquamarine-blue:
        label: 'Soee.CookieConsent:Settings:palettes.aquamarine-blue'
        colors:
          popup:
            background: '#eaf7f7'
            text: '#5c7291'
          button:
            background: '#56cbdb'
            text: '#ffffff'
      prussian-blue:
        label: 'Soee.CookieConsent:Settings:palettes.prussian-blue'
        colors:
          popup:
            background: '#252e39'
          button:
            background: '#14a7d0'
      black-green:
        label: 'i18n'
        colors:
          popup:
            background: '#000'
            text: '#0f0'
          button:
            background: '#0f0'
      blue-purple:
        label: 'i18n'
        colors:
          popup:
            background: '#3937a3'
          button:
            background: '#e62576'
      cyclamen-violet:
        label: 'i18n'
        colors:
          popup:
            background: '#64386b'
            text: '#ffcdfd'
          button:
            background: '#f8a8ff'
            text: '#3f0045'
      blue-white:
        label: 'i18n'
        colors:
          popup:
            background: '#237afc'
          button:
            background: '#fff'
            text: '#237afc'
      sanguine-red:
        label: 'i18n'
        colors:
          popup:
            background: '#aa0000'
            text: '#ffdddd'
          button:
            background: '#ff0000'
